package Vista;

public class IngresoDatos extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public IngresoDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jTextNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jTextCedulaVieja = new javax.swing.JTextField();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelSueldo = new javax.swing.JLabel();
        jTextSueldo = new javax.swing.JTextField();
        jLabelHoraTrabajo = new javax.swing.JLabel();
        jTextDiasTrabajo = new javax.swing.JTextField();
        jTextHEDiurna = new javax.swing.JTextField();
        jLabelHED = new javax.swing.JLabel();
        jTextHENocturna = new javax.swing.JTextField();
        jLabelHEN = new javax.swing.JLabel();
        jLabelHEND = new javax.swing.JLabel();
        jTextHEDiurnaFestiva = new javax.swing.JTextField();
        jLabelHENF = new javax.swing.JLabel();
        jTextHENocturnaFestiva = new javax.swing.JTextField();
        jLabelARP = new javax.swing.JLabel();
        jTextARP = new javax.swing.JTextField();
        jLabelHRN = new javax.swing.JLabel();
        jTextHRN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNomina = new javax.swing.JTable();
        jButtonGuardar = new javax.swing.JButton();
        jButtonVer = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jButtonSeleccionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelFondo.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 380, -1));

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombres :");
        jPanelFondo.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        jTextCedula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextCedula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulaActionPerformed(evt);
            }
        });
        jTextCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCedulaKeyTyped(evt);
            }
        });
        jPanelFondo.add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 290, -1));

        jTextCedulaVieja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextCedulaVieja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextCedulaVieja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulaViejaActionPerformed(evt);
            }
        });
        jTextCedulaVieja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCedulaViejaKeyTyped(evt);
            }
        });
        jPanelFondo.add(jTextCedulaVieja, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 134, -1, 0));

        jLabelNombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre1.setText("Cedula:");
        jPanelFondo.add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 20));

        jLabelSueldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSueldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSueldo.setText("Sueldo:");
        jPanelFondo.add(jLabelSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, 20));

        jTextSueldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextSueldo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSueldoActionPerformed(evt);
            }
        });
        jTextSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSueldoKeyTyped(evt);
            }
        });
        jPanelFondo.add(jTextSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 120, -1));

        jLabelHoraTrabajo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHoraTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoraTrabajo.setText("Días de Trabajo:");
        jPanelFondo.add(jLabelHoraTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, 20));

        jTextDiasTrabajo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextDiasTrabajo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextDiasTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiasTrabajoActionPerformed(evt);
            }
        });
        jTextDiasTrabajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDiasTrabajoKeyTyped(evt);
            }
        });
        jPanelFondo.add(jTextDiasTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 60, -1));

        jTextHEDiurna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextHEDiurna.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextHEDiurna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHEDiurnaActionPerformed(evt);
            }
        });
        jTextHEDiurna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextHEDiurnaKeyTyped(evt);
            }
        });
        jPanelFondo.add(jTextHEDiurna, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 60, -1));

        jLabelHED.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHED.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHED.setText("Horas Extras Diurna:");
        jPanelFondo.add(jLabelHED, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, 20));

        jTextHENocturna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextHENocturna.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextHENocturna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHENocturnaActionPerformed(evt);
            }
        });
        jTextHENocturna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextHENocturnaKeyTyped(evt);
            }
        });
        jPanelFondo.add(jTextHENocturna, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 60, -1));

        jLabelHEN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHEN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHEN.setText("Horas Extras Nocturna:");
        jPanelFondo.add(jLabelHEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, -1, 20));

        jLabelHEND.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHEND.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHEND.setText("HE Diurna Dominical :");
        jPanelFondo.add(jLabelHEND, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, 20));

        jTextHEDiurnaFestiva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextHEDiurnaFestiva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextHEDiurnaFestiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHEDiurnaFestivaActionPerformed(evt);
            }
        });
        jTextHEDiurnaFestiva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextHEDiurnaFestivaKeyTyped(evt);
            }
        });
        jPanelFondo.add(jTextHEDiurnaFestiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 60, -1));

        jLabelHENF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHENF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHENF.setText("HE Nocturna Dominical:");
        jPanelFondo.add(jLabelHENF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, 20));

        jTextHENocturnaFestiva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextHENocturnaFestiva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextHENocturnaFestiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHENocturnaFestivaActionPerformed(evt);
            }
        });
        jTextHENocturnaFestiva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextHENocturnaFestivaKeyTyped(evt);
            }
        });
        jPanelFondo.add(jTextHENocturnaFestiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 60, -1));

        jLabelARP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelARP.setForeground(new java.awt.Color(255, 255, 255));
        jLabelARP.setText("N. ARP (1 - 6):");
        jPanelFondo.add(jLabelARP, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, -1, 20));

        jTextARP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextARP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextARP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextARPActionPerformed(evt);
            }
        });
        jTextARP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextARPKeyTyped(evt);
            }
        });
        jPanelFondo.add(jTextARP, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 240, 60, -1));

        jLabelHRN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHRN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHRN.setText("H.  Recargo Nocturno");
        jPanelFondo.add(jLabelHRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, 20));

        jTextHRN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextHRN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextHRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHRNActionPerformed(evt);
            }
        });
        jTextHRN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextHRNKeyTyped(evt);
            }
        });
        jPanelFondo.add(jTextHRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 60, -1));

        jTableNomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableNomina);

        jPanelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 840, 240));

        jButtonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jButtonVer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonVer.setForeground(new java.awt.Color(204, 0, 0));
        jButtonVer.setText("MOSTRAR");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, -1, -1));

        jButtonMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMenu.setForeground(new java.awt.Color(204, 0, 0));
        jButtonMenu.setText("MENÚ");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, -1, -1));

        jButtonActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonActualizar.setText("ACTUALIZAR");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, -1, -1));

        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonEliminar.setText("ELIMINAR");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        jButtonNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonNuevo.setForeground(new java.awt.Color(204, 0, 0));
        jButtonNuevo.setText("NUEVO");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 100, -1));

        jButtonSeleccionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSeleccionar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonSeleccionar.setText("SELECCIONAR");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NominaSmart");
        jPanelFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRO DE DATOS");
        jPanelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondo.jpg"))); // NOI18N
        jPanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulaActionPerformed

    private void jTextDiasTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiasTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiasTrabajoActionPerformed

    private void jTextHEDiurnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHEDiurnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHEDiurnaActionPerformed

    private void jTextHENocturnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHENocturnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHENocturnaActionPerformed

    private void jTextHEDiurnaFestivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHEDiurnaFestivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHEDiurnaFestivaActionPerformed

    private void jTextHENocturnaFestivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHENocturnaFestivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHENocturnaFestivaActionPerformed

    private void jTextSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSueldoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCedulaKeyTyped
        // TODO add your handling code here:
        char texto = evt.getKeyChar();
        if (((texto < '0')
                || (texto > '9'))
                && (texto != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        String datos = jTextCedula.getText();
        if (datos.length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextCedulaKeyTyped

    private void jTextSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSueldoKeyTyped
        // TODO add your handling code here:
        char texto = evt.getKeyChar();
        if (((texto < '0')
                || (texto > '9'))
                && (texto != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        String datos = jTextSueldo.getText();
        if (datos.length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextSueldoKeyTyped

    private void jTextDiasTrabajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDiasTrabajoKeyTyped
        // TODO add your handling code here:
        char texto = evt.getKeyChar();
        if (((texto < '0')
                || (texto > '9'))
                && (texto != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        String datos = jTextDiasTrabajo.getText();
        if (datos.length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextDiasTrabajoKeyTyped

    private void jTextHEDiurnaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextHEDiurnaKeyTyped
        // TODO add your handling code here:
        char texto = evt.getKeyChar();
        if (((texto < '0')
                || (texto > '9'))
                && (texto != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        String datos = jTextHEDiurna.getText();
        if (datos.length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextHEDiurnaKeyTyped

    private void jTextHENocturnaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextHENocturnaKeyTyped
        // TODO add your handling code here:
        char texto = evt.getKeyChar();
        if (((texto < '0')
                || (texto > '9'))
                && (texto != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        String datos = jTextHENocturna.getText();
        if (datos.length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextHENocturnaKeyTyped

    private void jTextHEDiurnaFestivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextHEDiurnaFestivaKeyTyped
        // TODO add your handling code here:
        char texto = evt.getKeyChar();
        if (((texto < '0')
                || (texto > '9'))
                && (texto != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        String datos = jTextHEDiurnaFestiva.getText();
        if (datos.length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextHEDiurnaFestivaKeyTyped

    private void jTextHENocturnaFestivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextHENocturnaFestivaKeyTyped
        // TODO add your handling code here
        char texto = evt.getKeyChar();
        if (((texto < '0')
                || (texto > '9'))
                && (texto != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        String datos = jTextHENocturnaFestiva.getText();
        if (datos.length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextHENocturnaFestivaKeyTyped

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTextARPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextARPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextARPActionPerformed

    private void jTextARPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextARPKeyTyped
        // TODO add your handling code here:
         char texto = evt.getKeyChar();
        if (((texto < '0')
                || (texto > '9'))
                && (texto != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        String datos = jTextARP.getText();
        if (datos.length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextARPKeyTyped

    private void jTextHRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHRNActionPerformed

    private void jTextHRNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextHRNKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHRNKeyTyped

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void jTextCedulaViejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulaViejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulaViejaActionPerformed

    private void jTextCedulaViejaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCedulaViejaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulaViejaKeyTyped

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizar;
    public javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtonGuardar;
    public javax.swing.JButton jButtonMenu;
    public javax.swing.JButton jButtonNuevo;
    public javax.swing.JButton jButtonSeleccionar;
    public javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelARP;
    private javax.swing.JLabel jLabelHED;
    private javax.swing.JLabel jLabelHEN;
    private javax.swing.JLabel jLabelHEND;
    private javax.swing.JLabel jLabelHENF;
    private javax.swing.JLabel jLabelHRN;
    private javax.swing.JLabel jLabelHoraTrabajo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableNomina;
    public javax.swing.JTextField jTextARP;
    public javax.swing.JTextField jTextCedula;
    public javax.swing.JTextField jTextCedulaVieja;
    public javax.swing.JTextField jTextDiasTrabajo;
    public javax.swing.JTextField jTextHEDiurna;
    public javax.swing.JTextField jTextHEDiurnaFestiva;
    public javax.swing.JTextField jTextHENocturna;
    public javax.swing.JTextField jTextHENocturnaFestiva;
    public javax.swing.JTextField jTextHRN;
    public javax.swing.JTextField jTextNombre;
    public javax.swing.JTextField jTextSueldo;
    // End of variables declaration//GEN-END:variables
}
